{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deciops.fullname" . }}-loki-config
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    common:
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            period: 24h
            prefix: index_
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 50
      max_streams_per_user: 10000
      max_global_streams_per_user: 50000
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
    tracing:
      enabled: false
{{- end }}