apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deciops.fullname" . }}-secrets
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.db_password }}
  DB_PASSWORD: {{ .Values.secrets.db_password | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwt_secret }}
  JWT_SECRET: {{ .Values.secrets.jwt_secret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redis_password }}
  REDIS_PASSWORD: {{ .Values.secrets.redis_password | b64enc | quote }}
  {{- else }}
  REDIS_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

---
{{- if .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deciops.externalDbSecret" . }}
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password }}
  {{- else }}
  password: {{ randAlphaNum 32 }}
  {{- end }}
{{- end }}