apiVersion: v1
kind: Service
metadata:
  name: {{ include "deciops.fullname" . }}-decision-engine
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.decisionEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9091
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "deciops.selectorLabels" . | nindent 4 }}
    app: decision-engine

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deciops.fullname" . }}-backend-bff
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backendBff.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "deciops.selectorLabels" . | nindent 4 }}
    app: backend-bff

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deciops.fullname" . }}-frontend
  labels:
    {{- include "deciops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deciops.selectorLabels" . | nindent 4 }}
    app: frontend
